env:
  CI_TWITCH_API2_FEATURES: "twitch_oauth2/all all unsupported deny_unknown_fields trace_unknown_fields"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - staging
      - trying

name: Code Coverage
jobs:
  coverage:
    name: Run test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Toolchain setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: llvm-tools-preview
      - name: Cache cargo binaries
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-nightly-cargo-bin-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.rust }}-cargo-target-cov-${{ hashFiles('**/Cargo.lock') }}
          recovery-keys: ${{ runner.os }}-${{ matrix.rust }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Install grcov
        run: if [[ ! -e ~/.cargo/bin/grcov ]]; then cargo install grcov; fi
      - name: Run tests
        run: cargo test --features {{ CI_TWITCH_API2_FEATURES }}
        env:
          RUSTFLAGS: '-Z instrument-coverage'
          RUSTDOCFLAGS: '-Z instrument-coverage -Z unstable-options --persist-doctests target/debug/doctestbins'
      - name: Run grcov
        run: grcov . --binary-path target/debug/deps/ -s . -t lcov --branch --ignore-not-existing --ignore '../**' --ignore '/*' -o coverage.lcov
      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov